# Generated by Django 5.0.6 on 2025-02-12 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStorage',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_education', models.CharField(max_length=300)),
                ('job_experience', models.CharField(choices=[('NR', 'Not requirement'), ('LT1', 'Less than 1 year'), ('1Y', '1 year'), ('2Y', '2 years'), ('3Y', '3 years'), ('4Y', '4 years'), ('5Y', '5 years'), ('GT5', 'Greater than 5 years')], default='NR', max_length=15)),
                ('job_responsibilities', models.TextField()),
                ('job_tech_skills', models.CharField(max_length=500)),
                ('job_soft_skills', models.CharField(max_length=500)),
                ('job_certificates', models.CharField(blank=True, max_length=255, null=True)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('job_start', models.DateTimeField()),
                ('job_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStorage',
            fields=[
                ('resume_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resume_name', models.CharField(max_length=100, null=True)),
                ('resume_email', models.EmailField(max_length=254, null=True)),
                ('resume_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('resume_path', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
                ('resume_date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume_education', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_experience', models.FloatField(default=0.0)),
                ('resume_tech_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_soft_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_certificates', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_status', models.CharField(choices=[('Passed', 'Passed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('resume_summary', models.TextField()),
                ('resume_score', models.FloatField(default=0.0)),
                ('resume_AI_explanation', models.TextField(blank=True, null=True)),
                ('resume_job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.jobstorage')),
            ],
        ),
    ]
